name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          docker compose build

      - name: Check types
        run: npm run check:types

      - name: Lint
        run: npm run lint

      - name: Validate migrations
        run: npm run validate-migrations
